### PR TITLE
Content for 0.0.4 release

### LINKED ISSUE #15: Absence data
[As documented in the library](https://github.com/SchmidtDSE/afscgap#presence-only), the official [NOAA API service provides presence-only data](https://www.fisheries.noaa.gov/foss/f?p=215%3A28), frustrating some analysis requiring absence data for proper aggregation. This is likely because inclusion of absence data could cause a dramatic increase in dataset size, taking it from around a million to many millions of records. That said, for users who can handle those data sizes like through iteration-only aggregation, access to that information is important. Those records can be inferred by using the official [NOAA flat file for hauls in RACEBASE](https://www.fisheries.noaa.gov/inport/item/22008.).

This issue proposes adding a new keyword to the `query` method called `presence_only` which defaults to true. If set to false, the library will transparently download the [hauls file](https://console.cloud.google.com/storage/browser/_details/nmfs_odp_afsc/RACE/GAP/RACEBASE%20Database%3B%20Haul%20Table.csv?pli=1) and yield records with a zero catch from its iterator after API-returned record exhaustion.

Specifically, if set to false, the library would:

 - Record the set of species  observed from API service returned results.
 - Record the set of  hauls (survey/cruse/hauls/species combinations) observed from API service returned results.
 - Return records normally while records remain available from the API service.
 - Upon exhaustion of the API service results, download the ~1M hauls flat file.
 - For each species observed in the API returned results check if that species had a record for each haul (survey/cruse/haul combination) reported in the flat file.
 - For any hauls without the species record, yield an 0 catch record from the iterator for that haul.

This provides absence data without necessarily requiring a very large dataset to be held in memory at once.

### LINKED ISSUE #17: Add short hand query for range, less than, greater than
To avoid pushing users into ORDS syntax, adding a range option with infinity on either side is likely helpful.

### LINKED ISSUE #18: Add warning if using absense data along with ability to suppress that warning.
Related to #15, warn the user that the dataset could be quite large but offer a way to suppress that warning.

### LINKED ISSUE #19: Move all type definitions to util
For style, should centralize all of the type definitions using primitives.

### PR DESCRIPTION
**Pull request by sampottinger**
Closes #15
Closes #17 
Closes #18 
Closes #19

### CODE REVIEW

**Comment by sampottinger** [comment]
Implemented and tested but not documented. Working on that now...

**Comment by sampottinger** [comment]
@gizarp marked ready for review

**Review by gizarp — COMMENTED** [review]
Thanks for all these improvements! 🙌🏼 

The restructuring looks good on my end, and I think the way absence data is handled and explained is satisfactory. 

The example `cod.ipynb` notebook already looks good, and I have no doubt the finishing touches (citations, binder link) will be OK. I have one question though: the library only relies on `requests`, but the notebook clearly needs to use more tools (e.g., `pandas`, `matplotlib` etc). When we build a binder link, would that create an environment in which this notebook can run, or would it be based on the library requirements only? 🤔 

(😅 this is me learning binder via PR reviews!)

**Comment by sampottinger** [comment]
Awesome thanks @gizarp! Yeah I'm hoping that, when I direct binder to a subdirectory, that it sees a requirements file under notebooks but I'm inclined to try that on another PR.

**Comment by gizarp** [comment]
Approving this as we will likely be better equipped to deal with binder deployment directly on `main`.

**Pull request merged**
