### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by sampottinger**
Everything needed for the 0.0.1 release.

- [x] Implement tests
- [x] Implement CI / CD
- [x] Implement library specification
- [x] Pass checks
- [x] Docstrings

### CODE REVIEW

**Comment by gizarp** [comment]
Nice work! I'm working more formally through the PR and here are initial comments. 

- Installing the branch locally in editable mode works fine, but then import in Python fails on my end due to a TypeError in `client.py`: 

```
>>> import afscgap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/giuliazarpellon/GitProjects/afscgap/afscgap/__init__.py", line 34, in <module>
    import afscgap.client
  File "/Users/giuliazarpellon/GitProjects/afscgap/afscgap/client.py", line 63, in <module>
    class Cursor(typing.Iterable[afscgap.model.Record]):
  File "/Users/giuliazarpellon/GitProjects/afscgap/afscgap/client.py", line 204, in Cursor
    def get_invalid(self) -> queue.Queue[dict]:
TypeError: 'type' object is not subscriptable
```

- The README (in the `main` branch) is very useful to provide context and motivation. To make it even more clear, I would suggest to point to the "Data structure/Schema" section of the README already in "Usage". This way, if somebody is not familiar with this data in advance (like me!), they can peer to a later section before continuing, and the basic usage examples will make more sense. 
- This might be a very silly question, but what's the rationale behind having a `page_offset`, `offset`, `start_offset`? 
- I spotted a few typos that we can fix later on (really minor things), but the third column of the getter table in the README seems to be skewed by one rows with respect to the rest. Could you double check that?

Thanks!

**Comment by gizarp** [comment]
Note: this was run on a conda env with Python 3.8.16 (specifications suggest Python >=3.7)

**Comment by sampottinger** [comment]
Thanks @gizarp! This is very helpful. I'll tackle the type error now and get to the others shortly.

> Installing the branch locally in editable mode works fine, but then import in Python fails on my end due to a TypeError 

Ah sorry this is because Queue only became subscriptable in Python 3.9 and I see you are running with Python 3.8 (thanks for catching that). See https://bugs.python.org/issue33315. 

> To make it even more clear, I would suggest to point to the "Data structure/Schema" section of the README already in "Usage". 

Really good point. I'll update that to direct to that earlier.

> This might be a very silly question, but what's the rationale behind having a page_offset, offset, start_offset?

Not at all. I might have made a mistake in there. My thought was `start_offset` for a query as the offset used after the initial iteration will change and `page_offset` for asking for individual pages. I'll double check that it was used consistently though.

> I spotted a few typos that we can fix later on (really minor things), but the third column of the getter table in the README seems to be skewed by one rows with respect to the rest. Could you double check that?

Good catch I'll take a look.

**Comment by sampottinger** [comment]
@gizarp - https://github.com/SchmidtDSE/afscgap/pull/1/commits/ec69936982cf52f8ab3b9737af2a82ac80c3a92c should hopefully fix the type issue.

**Comment by sampottinger** [comment]
Cool cool cool! So, I think we have the following left for merge here:

- [ ] Check offset consistency
- [ ] Update readme to point to schema in intro

**Comment by sampottinger** [comment]
Thanks @gizarp for https://github.com/SchmidtDSE/afscgap/pull/1/commits/ffcd07a77b14713ae4decc913bd08a9469b6188e!

**Review by gizarp — COMMENTED** [review]
Thanks @sampottinger for fixing the TypeError without necessarily relying on higher Python! 

The README snippets run as expected now, and the consistency throughout is great. I also appreciated the issues opened on badges and gh pages. 

On my end, I'll be happy to accept the PR when the two todos above are cleared!

**Pull request merged**
