### PR TITLE
JOSS Paper Draft

### PR DESCRIPTION
**Pull request by sampottinger**
JOSS Paper Draft and minor documentation updates.

### CODE REVIEW

**Comment by sampottinger** [comment]
Sorry @gizarp just fixed three things in the citations. Should be sorted.

**Comment by sampottinger** [comment]
Got the diagrams in with a little bit of trimming. 10 words below the limit 😅

**Review by gizarp — APPROVED** [review]
Great job! I'm approving, and only have three minor fixes to suggest/correct:

- [line 27] When introducing acronyms, what is RACE? Should it just stay outside the parenthesis? 
> The National Oceanic and Atmospheric Administration's Alaska Fisheries Science Center (NOAA AFSC) RACE runs...

- [line 35] I would suggest to put the example between parenthesis: 
> Many types of analysis (e.g., aggregating species catch per unit effort by geohash) require information not just about where a species was present but also where it was not [@geohash].

- [line 51] typo in "proceedure" --> "procedure"

Thank you!

**Comment by sampottinger** [comment]
It looks like I may need to link to this in my pyopensci submission so will merge. Can reverse if they need me to. Thanks @gizarp !

**Pull request merged**
