### PR TITLE
Preparation for implementation of first version of viz tool

### PR DESCRIPTION
**Pull request by sampottinger**

### CODE REVIEW

**Comment by sampottinger** [comment]
Might need to split these into two.

**Comment by sampottinger** [comment]
Hey @gizarp! Not sure if you have a quick minute for this but I am getting a d3-based visualization up for the first part of pyafscgap.org. I've got a little new logic to compile data to a geohash aggregated sqlite database to support that viz because going to the API service is too slow. :( LMK if you have time and thanks!

**Comment by gizarp** [comment]
Sure! Happy to have a look :)

**Comment by sampottinger** [comment]
Thanks!

**Comment by sampottinger** [comment]
For this one, I may need an approve without the merge. I just want to check the CI/CD stuff is still behaving when it goes to main. Thanks!

**Review by gizarp — APPROVED** [review]
Looks good on my end! 

I'm not 100% sure I understand the rationale behind the combination of `SimplifiedRecord` objects via keys in `afscgapviz/model.py`, and in which sense these records get combined on the different fields. Given it's an operation on internal representations only, we can discuss this more and potentially extend it later on!

**Comment by sampottinger** [comment]
> keys in afscgapviz/model.py, and in which sense these records get combined on the different fields
Thanks @gizarp! Yeah happy to talk more live!

**Pull request merged**
